mybatis files
SuperWebMonkey/BankApplication pull request #6
Opened 2023-01-31 18:18 UTC by SuperWebMonkey

2023-02-02 07:26 UTC, ankochergin commented on src/main/java/db/dao/IFlightDAO.java
> +    Flight getFlightByPrice(double db_price);
```suggestion
    Flight getFlightByPrice(double price);
```

2023-02-03 07:32 UTC, ankochergin requested changes
please review whole code and make sure all your variables, methods and classes have correct naming

2023-02-03 07:32 UTC, ankochergin commented on src/main/java/db/dao/IOrderDAO.java
> +    Order getOrderByPayment(double db_payment);
```suggestion
    Order getOrderByPayment(double payment);
```

2023-02-06 07:51 UTC, ankochergin requested changes

2023-02-06 07:51 UTC, ankochergin commented on src/main/java/db/patterns/CustomerBuilder.java
> +
rename methods to **set**CustomerId or **with**CustomerId
method name always should show action

2023-02-06 07:51 UTC, ankochergin commented on src/main/java/db/patterns/DatabaseFactory.java
> +        return null;
do not return null

2023-02-06 07:51 UTC, ankochergin commented on src/main/java/db/patterns/DatabaseFactory.java
> +        if (type.equals("jdbc"))
1. using of `equals` here is not null-safe. It'll throw NullPointerException if type is null. you should always use `equals` method on variable which is 100% not null. In this case `"jdbc".equals(type)`

2023-02-06 07:51 UTC, ankochergin commented on src/main/java/db/patterns/DatabaseFactory.java
> +        if (type.equals("jdbc"))
2. I think types of the database can be moved to enum

2023-02-06 07:51 UTC, ankochergin commented on src/main/java/db/patterns/DatabaseFactory.java
> +        if (type.equals("jdbc"))
3. You return 2 different types of objects, I would suggest to have DAO factories for both jdbc and mybatis and get proper DAO factory by enum

2023-02-08 07:34 UTC, ankochergin commented on src/main/java/db/patterns/JDBCDAOFactory.java
> +                throw new UnknownDatabaseTypeException("Unknown database type exception.");
I think proper message here should be "Unknown model provided"

2023-02-08 07:34 UTC, ankochergin commented on src/main/java/db/patterns/MyBatisDAOFactory.java
> +                throw new UnknownDatabaseTypeException("Unknown database type exception.");
same here. This factory is creating dao, not connections

2023-02-12 21:55 UTC, SuperWebMonkey commented on src/main/java/db/patterns/MyBatisDAOFactory.java
> +                throw new UnknownDatabaseTypeException("Unknown database type exception.");
What data type should be returned if it is not the DAO class?

2023-02-14 03:21 UTC, merged